Disable Mac

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -132,85 +132,85 @@ jobs:
 #          path: /home/runner/work/pgmoneta/pgmoneta/build/doc
 #          retention-days: 90
 
-  build-macos:
-    runs-on: macos-latest
-    env:
-      PGMONETA_ROOT: ${{ github.workspace }}
-      BUILD_DIR: ${{ github.workspace }}/build
-      POSTGRESQL_VERSION: "@17"
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-      - name: Set up Homebrew
-        id: set-up-homebrew
-        uses: Homebrew/actions/setup-homebrew@master
-      - name: Install dependencies
-        run: |
-          brew update
-          brew install \
-            libev \
-            docutils \
-            libarchive \
-            check \
-            postgresql${POSTGRESQL_VERSION} \
-            libssh \
-            doxygen \
-            pandoc
-      - name: Install pdflatex
-        run: |
-          curl -LO https://mirror.ctan.org/systems/mac/mactex/MacTeX.pkg && sudo installer -pkg MacTeX.pkg -target /
-          echo "/Library/TeX/texbin" >> $GITHUB_PATH
-      - name: Install eisvogel template for Pandoc
-        run: |
-          wget https://github.com/Wandmalfarbe/pandoc-latex-template/releases/download/v3.2.0/Eisvogel-3.2.0.tar.gz
-          tar -xzf Eisvogel-3.2.0.tar.gz
-          mkdir -p ~/.local/share/pandoc/templates
-          mv Eisvogel-3.2.0/eisvogel.latex ~/.local/share/pandoc/templates/
-      - name: Install Devanagari font for Hindi Documentation
-        run: |
-          brew install --cask font-noto-sans-devanagari
-          fc-list | grep "Noto Sans Devanagari"
-      - name: Add PostgreSQL to PATH
-        run: |
-          echo "$(brew --prefix postgresql${POSTGRESQL_VERSION})/bin" >> $GITHUB_PATH
-      - name: Build with Clang
-        run: |
-          mkdir -p $BUILD_DIR
-          cd $BUILD_DIR
-          export CC=$(xcrun -find clang)
-          cmake -DCMAKE_BUILD_TYPE=Debug ..
-          make -j$(sysctl -n hw.ncpu)
-      # - name: Run tests with Clang build
-      #   working-directory: ${{ env.BUILD_DIR }}
-      #   run: $(which bash) ./testsuite.sh
+# build-macos:
+#   runs-on: macos-latest
+#   env:
+#     PGMONETA_ROOT: ${{ github.workspace }}
+#     BUILD_DIR: ${{ github.workspace }}/build
+#     POSTGRESQL_VERSION: "@17"
+#   steps:
+#     - name: Checkout repository
+#       uses: actions/checkout@v4
+#     - name: Set up Homebrew
+#       id: set-up-homebrew
+#       uses: Homebrew/actions/setup-homebrew@master
+#     - name: Install dependencies
+#       run: |
+#         brew update
+#         brew install \
+#           libev \
+#           docutils \
+#           libarchive \
+#           check \
+#           postgresql${POSTGRESQL_VERSION} \
+#           libssh \
+#           doxygen \
+#           pandoc
+#     - name: Install pdflatex
+#       run: |
+#         curl -LO https://mirror.ctan.org/systems/mac/mactex/MacTeX.pkg && sudo installer -pkg MacTeX.pkg -target /
+#         echo "/Library/TeX/texbin" >> $GITHUB_PATH
+#     - name: Install eisvogel template for Pandoc
+#       run: |
+#         wget https://github.com/Wandmalfarbe/pandoc-latex-template/releases/download/v3.2.0/Eisvogel-3.2.0.tar.gz
+#         tar -xzf Eisvogel-3.2.0.tar.gz
+#         mkdir -p ~/.local/share/pandoc/templates
+#         mv Eisvogel-3.2.0/eisvogel.latex ~/.local/share/pandoc/templates/
+#     - name: Install Devanagari font for Hindi Documentation
+#       run: |
+#         brew install --cask font-noto-sans-devanagari
+#         fc-list | grep "Noto Sans Devanagari"
+#     - name: Add PostgreSQL to PATH
+#       run: |
+#         echo "$(brew --prefix postgresql${POSTGRESQL_VERSION})/bin" >> $GITHUB_PATH
+#     - name: Build with Clang
+#       run: |
+#         mkdir -p $BUILD_DIR
+#         cd $BUILD_DIR
+#         export CC=$(xcrun -find clang)
+#         cmake -DCMAKE_BUILD_TYPE=Debug ..
+#         make -j$(sysctl -n hw.ncpu)
+#     # - name: Run tests with Clang build
+#     #   working-directory: ${{ env.BUILD_DIR }}
+#     #   run: $(which bash) ./testsuite.sh
 
-      # - name: Clean up after Clang tests
-      #   working-directory: ${{ env.BUILD_DIR }}
-      #   run: $(which bash) ./testsuite.sh clean
+#     # - name: Clean up after Clang tests
+#     #   working-directory: ${{ env.BUILD_DIR }}
+#     #   run: $(which bash) ./testsuite.sh clean
 
-      - name: Show logs on failure
-        if: failure()
-        working-directory: ${{ env.BUILD_DIR }}
-        run: |
-          cat ./log/logfile || echo "logfile not found"
-          cat ./log/pgmoneta.log || echo "pgmoneta.log not found"
+#     - name: Show logs on failure
+#       if: failure()
+#       working-directory: ${{ env.BUILD_DIR }}
+#       run: |
+#         cat ./log/logfile || echo "logfile not found"
+#         cat ./log/pgmoneta.log || echo "pgmoneta.log not found"
 
-      - name: Upload logs on failure
-        if: failure()
-        uses: actions/upload-artifact@v4
-        with:
-          name: macos-build-logs
-          path: |
-            ${{ env.BUILD_DIR }}/log/
-            /tmp/*.log
-          retention-days: 7
+#     - name: Upload logs on failure
+#       if: failure()
+#       uses: actions/upload-artifact@v4
+#       with:
+#         name: macos-build-logs
+#         path: |
+#           ${{ env.BUILD_DIR }}/log/
+#           /tmp/*.log
+#         retention-days: 7
 
-      - name: Upload Generated Documentation Artifacts
-        uses: actions/upload-artifact@v4
-        with:
-          name: macos-generated-docs
-          path: ${{ env.BUILD_DIR }}/doc/
-          retention-days: 7
+#     - name: Upload Generated Documentation Artifacts
+#       uses: actions/upload-artifact@v4
+#       with:
+#         name: macos-generated-docs
+#         path: ${{ env.BUILD_DIR }}/doc/
+#         retention-days: 7
 
 #  build-freebsd:
 #    runs-on: ubuntu-latest
